# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: History and Trump
email: c.blevins@northeastern.edu
description: > # this means to ignore newlines until "baseurl:"
  Course website for HIST 1200/1201: History and Trump. Northeastern University, Fall 2017
baseurl: "/sp18-space-place" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site
#twitter_username: historying
#github_username:  cblevins
university: Northeastern University
course_number: "HIST 1200/1201"
semester: "Fall 2017"
room: "456 Ryder Hall"
meetingtime: "Mon/Wed 2:50-4:30pm"

instructor: Cameron Blevins
email: c.blevins@northeastern.edu
office: "237 Meserve Hall"
officehours: "Wed. 4:45-5:45pm, and by appointment"

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
